version: '3'
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server --inline true 
    volumes:
      - .:/onebitflix
      - app-gems:/app-gems
    ports:
      - '3035:3035'
  
  app:
    depends_on:
      - postgres
      - webpacker
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: bash start
    volumes:
      - .:/onebitflix
      - app-gems:/app-gems
    env_file:
      - '.env.docker'

volumes:
  postgres:
  app-gems:
  webpacker: