version: '3'
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: bin/webpack-dev-server --inline true
    volumes:
      - .:/onebitflix
    ports:
      - '3035:3035'
    tty: false
    stdin_open: false
  
  app:
    depends_on:
      - postgres
      - webpacker
    build: .
    env_file:
      - '.env.docker'
    command: bash start
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitflix
      - app-gems:/app-gems
    stdin_open: true
    tty: true

volumes:
  postgres:
  app-gems:
  webpacker: