version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/onebitflix
    ports:
      - "8080:8080"
  
  app:
    build: .
    command: bash start
    volumes:
      - .:/onebitfli 
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: