version: '3'
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/onebitflix
    ports:
      - "8080:8080"
  
  app:
    depends_on:
      - postgres
      - webpacker
    build: .
    command: bash start
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitflix
      - app-gems:/app-gems
    stdin_open: true
    tty: true


  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  app-gems: